source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/baijia/specs.git'

platform :ios, '8.0'
# inhibit_all_warnings!

post_install do |installer|
    installer.pods_project.root_object.attributes["CLASSPREFIX"] = "BJL"
    installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "BaijiaYun"
end

target 'BJLiveCore' do
    
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # dev
    # pod 'BJLiveBase', :path => '../../../BJLiveBase/'
    pod 'BJLiveCore', :path => '../'
    
    # pod 'BJLiveCore', '~> 1.0.1'
    
    # demo
    pod 'Masonry'
    
    # debug
    pod 'FLEX', '~> 2.0', :configurations => ['Debug']
    
    target 'BJLiveCoreTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'BJLiveCoreUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
