source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/baijia/specs.git'

platform :ios, '8.0'
# inhibit_all_warnings!

target 'BJLiveCore' do
    
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # dev
    # pod 'BJLiveCore'
    # pod 'BJLiveCore', '0.2.4.5-beta'
    pod 'BJLiveCore', :path => '../'
    
    # demo
    pod 'Masonry'
    pod 'M9Dev'
    
    # debug
    pod 'FLEX', '~> 2.0', :configurations => ['Debug']
    
    target 'BJLiveCoreTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'BJLiveCoreUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
